apiVersion: v1
kind: Service
metadata:
  name: assembly-voter-svc
  namespace: assembly-voter-ns
spec:
  selector:
    app: assembly-voter-api
    tier: backend
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080 # On Windows with docker, this is specific number port don`t work. Needs 'port forward' otherwise creates number port randomly.
  type: NodePort