apiVersion: v1
kind: Service
metadata:
  name: postgres-db-svc
  namespace: assembly-voter-ns
spec:
  selector:
    app: postgres-db
    tier: database
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP