apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-cm
  namespace: assembly-voter-ns
data:
  host: "rabbitmq-svc.assembly-voter-ns.svc.cluster.local" # To connect to the pod/host, follow the patterns: <service-name.namespace.svc.cluster.local>
  port: "5672"
  default-user: "admin"
  default-pass: "admin"